services:
  server:
    container_name: server
    image: nginx:1.28.0
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./../coaster/:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - coaster
  coaster:
    container_name: coaster
    image: coaster
    build:
      context: ./../coaster
      dockerfile: ./../docker/php/Dockerfile
    volumes:
      - ./../coaster/:/var/www/html
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - cache
    environment:
      - XDEBUG_MODE=coverage
  cache:
    container_name: cache
    image: redis:8.0.2
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
