services:
  server:
    image: nginx:1.28.0
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./../coaster/:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - coaster
  coaster:
    container_name: coaster
    image: coaster
    build:
      context: ./../coaster
      dockerfile: ./../docker/php/Dockerfile
    volumes:
      - ./../coaster/:/var/www/html
